### ISSUE TITLE
CSS Errors

### ISSUE THREAD

**Issue by mthierba** [Crunch-io/crunch-js-components#16]
The bundled CSS has some issues, most importantly, it can't be parsed as valid CSS in various places. We're using CSSO in our app where we're integrating crunch-js-components, and that one chokes on those issues and effectively breaks the build.

Most prominently, this block in `variables-accordion`:
```
    .variable-browser
    overflow hidden
    browseable-item-min-width = 270px
    browseable-item-max-width = 540px
    browsable-item-flex-basis = (browseable-item-max-width + browseable-variable-h-space * 2)
    navigation-min-width = 16px
    navigation-max-width = navigation-min-width
```
... transforms into that CSS:
```
variables-accordion .variable-browser.next:hover,
variables-accordion overflow hidden.next:hover,
variables-accordion browseable-item-min-width = 270px.next:hover,
variables-accordion browseable-item-max-width = 540px.next:hover,
variables-accordion browsable-item-flex-basis = (browseable-item-max-width + browseable-variable-h-space * 2).next:hover,
variables-accordion navigation-min-width = 16px.next:hover,
variables-accordion navigation-max-width = navigation-min-width.next:hover,
variables-accordion .navigate.next:hover {
  background-image: url("right_hover.png");
}
```

Which, AFAIK, is not valid CSS. [The W3C CSS Validator thinks so, too.](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fbeta.crunch.io%2Fwhaam-2.2.3-rc-1590-92d8b4e%2Fstyles.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en)

We've had to manually patch your `crunch-js-components.css` and overwrite the version contained in the package, but that's only a very temporary fix at best. It would be great if you could fix these things at the source.

**Comment by enriquecastl** [comment]
Thanks for the report @mthierba 

It's weird that stylus is leaving variables declarations after the stylesheets are pre processed. I'll find out the reason and work on a solution.
